### ISSUE TITLE
Publishing to Azure Web App in a virtual application directory creates invalid web.config

### ISSUE THREAD

**Issue by rmja** [aspnet/Home#1203]
The web.config generated for a virtual application in an Azure Web App virtual directory uses the configuration values of the main site.

Example of invalid (default) web.config:

```
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpplatformhandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
    </handlers>
    <httpPlatform processPath="%home%\site\approot\web.cmd" arguments="" stdoutLogEnabled="false" stdoutLogFile="\\?\%home%\LogFiles\stdout.log" startupTimeLimit="3600"></httpPlatform>
  </system.webServer>
</configuration>
```

Example of a valid web.config:

```
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpplatformhandler-api" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
    </handlers>
    <httpPlatform processPath="%home%\site\api\approot\web.cmd" arguments="" stdoutLogEnabled="false" stdoutLogFile="\\?\%home%\LogFiles\stdout-api.log" startupTimeLimit="3600"></httpPlatform>
  </system.webServer>
</configuration>
```

**Comment by GuardRex** [comment]
https://github.com/aspnet/IISIntegration/issues/14
https://github.com/aspnet/Hosting/issues/416#issuecomment-149046552

**Comment by rmja** [comment]
Yes, i found them. The site is working in the virtual directory. The only problem is the transformation of the web.config file.

-----Oprindelig meddelelse-----
Fra: "Luke Latham" <notifications@github.com>
Sendt: ‎30-‎12-‎2015 17:50
Til: "aspnet/Home" <Home@noreply.github.com>
Cc: "rmja" <rmja@laesoe.org>
Emne: Re: [Home] Publishing to Azure Web App in a virtual applicationdirectory creates invalid web.config (#1203)

aspnet/IISIntegration#14
aspnet/Hosting#416 (comment)

**Comment by GuardRex** [comment]
I think @Tratcher was saying to make the `path="*"` in the base app ... https://github.com/aspnet/IISIntegration/issues/44#issuecomment-162644550 ... but I might be mis-reading it.

**Comment by GuardRex** [comment]
Yeah ... you probably were doing that now! Why does it always take a minimum of two cups of coffee to wake me up. Maybe @Fosol will jump in and tell us what he did here. I'd like to link to it.

**Comment by Fosol** [comment]
My memory isn't so great.  I remember two different problems with the web.config file.  
1) There was an attribute that needed to be removed in the published web.config.  I think it was something to do with security though.
2) If this is a virtual application under a parent you will need to remove the handlers since the parent will already have registered the httpPlatformHandler.  I think I just did a <clear/> before it in the subapplication.

**Comment by GuardRex** [comment]
Ah yes. That 2nd point is the critical bit to know for this.

I think the first issue you mentioned was fixed in RC1. That's the
forwarding for Windows auth.

**Comment by rmja** [comment]
I see. But how about the process path then? It is still wrong and points to the main app web.cmd

**Comment by GuardRex** [comment]
Are you on RC1-final with tooling updated? If memory serves, the parent app
path to web was ok as of RC1-final. The Map workaround takes care of the
child apps within. Those child apps don't get a handlers section.

I wish I had up a test app on my own. If u can't get it working by the time
I get to the office, I'll set one up and work thru it with you.

**Comment by rmja** [comment]
Yes, I am on rc1 final and have tooling updated.
I get that the sub app should not have a handlers section, but it must have a web.config with a httpplatform element and a processpath, right?

-----Oprindelig meddelelse-----
Fra: "Luke Latham" <notifications@github.com>
Sendt: ‎30-‎12-‎2015 21:16
Til: "aspnet/Home" <Home@noreply.github.com>
Cc: "rmja" <rmja@laesoe.org>
Emne: Re: [Home] Publishing to Azure Web App in a virtual applicationdirectory creates invalid web.config (#1203)

Are you on RC1-final with tooling updated? If memory serves, the parent app
path to web was ok as of RC1-final. The Map workaround takes care of the
child apps within. Those child apps don't get a handlers section.

I wish I had up a test app on my own. If u can't get it working by the time
I get to the office, I'll set one up and work thru it with you.

**Comment by GuardRex** [comment]
I didn't think so. Web.config, yes, but leave that httpPlatform element out
of the child web.config files, too, and see what happens.

I'm really curious about it. I'm leaving the gym now, I'll set one up, too,
when I get back.

**Comment by GuardRex** [comment]
@rmja I'm getting multiple entry point exceptions in the parent project. How did you add the child project to the parent project in VS? ... If it's not added there and you have the child project completely separate from the parent in VS (literally two stand-alone separate projects), are you then just publishing the child project to the parent's publish output (into a folder within that publish output) ... then kicking that payload up to Azure? ... It's been a long, long time since I've set one of these up ... like .NET 2.0 days.

**Comment by rmja** [comment]
@GuardRex I will try and detail my setup.

First, in Azure under the web app application settings:
![image](https://cloud.githubusercontent.com/assets/2112306/12064094/811a47ee-afba-11e5-9996-369533624ead.png)

I have created two completely independent web projects in Visual Studio. One for the root '/' default site, and one for the api.
The publication profiles for the two sites are:
For the root site:
![image](https://cloud.githubusercontent.com/assets/2112306/12064115/32c0916a-afbb-11e5-9ec6-8a3c6960ba19.png)

For the api site (note the added `/api` in site name and destination url):
![image](https://cloud.githubusercontent.com/assets/2112306/12064119/54bb84b4-afbb-11e5-9aca-76dfb48669a5.png)

The main site does not know anything about the api site at all. The IIS fix is applied for the /api site such that in `Startup.cs` the `Configure()` is replaced as follows:

```
public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
        {
            app.Map("/api", app1 => Configure1(app1, loggerFactory));
        }

        public void Configure1(IApplicationBuilder app, ILoggerFactory loggerFactory)
        {
              // Configure stuff here
        }
```

That is all. The only problem that remains is that the web.config generated when publishing the /api site is processPath to the `web.cmd` entry point of the /api site. That is: The processPath is incorrectly set to `%home%\site\approot\web.cmd` and not `%home%\site\api\approot\web.cmd` which follows the Azure configuration I described in the beginning.

Hope it helps:) And happy new year!

**Comment by GuardRex** [comment]
@rmja Where is your `global.json` file relative to the rest of the project files?

https://github.com/aspnet/Home/issues/1147
https://github.com/aspnet/dnx/issues/3229
https://github.com/aspnet/Hosting/issues/364#issuecomment-156381798

... if so, create a new proj and confirm that VS has put the `global.json` file outside of the `src` folder, where the rest of the proj files will be.

Of course, the end game we're going for is to have that `processPath` be relative ...
```
processPath="..\approot\web.cmd"
```
... the fact that you're not getting that by default when you VS publish means the tooling is confused.

Another one of interest talks about the wrong version of the HttpPlatformHander on the system ... You might want to check in Programs & Features on your dev box and absolutely confirm the version shows up in the name as v1.2. https://github.com/aspnet/Hosting/issues/412 and https://github.com/aspnet/Hosting/issues/432 and the next comment from @davidfowl to https://github.com/aspnet/Hosting/issues/364#issuecomment-148991810

**Comment by rmja** [comment]
@GuardRex I will go through the details tomorrow, but I am pretty sure that the httpplatformhandler has the correct version on azure and also on my dev machine. And global.json is outside of the src folder in where both websites are located.
Note that it all works on my dev machine. And publishing to file system works with a correct relative path. The problem only shows when publishing the sub site directly to azure. 

-----Oprindelig meddelelse-----
Fra: "Luke Latham" <notifications@github.com>
Sendt: ‎31-‎12-‎2015 18:40
Til: "aspnet/Home" <Home@noreply.github.com>
Cc: "rmja" <rmja@laesoe.org>
Emne: Re: [Home] Publishing to Azure Web App in a virtual applicationdirectory creates invalid web.config (#1203)

@rmja Where is your global.json file relative to the rest of the project files?
#1147
aspnet/dnx#3229
aspnet/Hosting#364 (comment)
... if so, create a new proj and confirm that VS has put the global.json file outside of the src folder, where the rest of the proj files will be.
Of course, the end game we're going for is to have that processPath be relative ...
processPath="..\approot\web.cmd"
... the fact that you're not getting that by default when you VS publish means the tooling is confused.
Another one of interest talks about the wrong version of the HttpPlatformHander on the system ... You might want to check in Programs & Features on your dev box and absolutely confirm the version shows up in the name as v1.2. aspnet/Hosting#412 and aspnet/Hosting#432 and the next comment from @davidfowl to aspnet/Hosting#364 (comment)

**Comment by GuardRex** [comment]
@rmja On your local box ... That problem seems to occur when tooling has the wrong version locally. The generated `web.config` was getting the wrong path for those cats when they have the earlier version installed on their dev box. Of course, you probably do have the right one installed locally ... and since this isn't the old `global.json`-in-the-wrong-spot issue, we'll prob have to dig more into it.

I'm going to be free at some point later tonight ushering in the New Year on .NET 5 :tada:. I'm going to try and replicate your layout here. If my tooling works and provides that relative path correctly, then I'm going to guess your VS tooling config is somehow amiss. I'll ping you back ... 

and Happy New Year! :tada: :fireworks: :tada: :fireworks: :tada: :fireworks:

**Comment by GuardRex** [comment]
@rmja Actually, now that I think about it ... my tooling is working correctly. You're just publishing locally ... that's all I'm doing. My path always comes out relative.

Check Programs & Features locally. You should explicitly see "1.2" in the name ...

![capture](https://cloud.githubusercontent.com/assets/1622880/12067639/450c23c4-afb2-11e5-9323-e202118beaa6.PNG)

**Comment by rmja** [comment]
@GuardRex I can confirm now that I have HTTP Platform Handler 1.2. When publishing the sub site to Azure, the processPath still comes out as the absolute path `%home%\site\approot\web.cmd` and with the handlers section:

```
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpplatformhandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
    </handlers>
    <httpPlatform processPath="%home%\site\approot\web.cmd" arguments="" stdoutLogEnabled="false" stdoutLogFile="\\?\%home%\LogFiles\stdout.log" startupTimeLimit="3600"></httpPlatform>
  </system.webServer>
</configuration>
```

Instead of the working:
```
<configuration>
  <system.webServer>
    <httpPlatform processPath="..\approot\web.cmd" arguments="" stdoutLogEnabled="false" stdoutLogFile="\\?\%home%\LogFiles\stdout.log" startupTimeLimit="3600"></httpPlatform>
  </system.webServer>
</configuration>
```

**Comment by GuardRex** [comment]
@rmja Good morning ... I'm setting it up now. I'll get back to you soon.

**Comment by GuardRex** [comment]
@rmja No dice ... not working here either ... as least insofar as Azure Web Apps is concerned ... at least insofar as the descriptions of the workaround have been posted. I consistently get a 500 from the child app no matter the configuration of the `app.Map()`, Azure vdir, and `Configure()`/`Configure1()` in the child app. You can remove the child app's `processPath` by removing (or commenting out) the entire `httpPlatform` element; however, the comment that you can drop the `handlers` element from the child app by removing it doesn't work ... VS publish just adds it back.

If there was anything else done in the apps, maybe @PeterJakubik will jump in and tell us coming off his success with https://github.com/aspnet/Hosting/issues/416#issuecomment-149046552.

Apparently, the workaround will work in IIS proper, since that's how its been reported. I'll try again when they hit rc2-final. https://github.com/aspnet/IISIntegration/issues/14.

**Comment by aspnet-hello** [comment]
This issue is being closed because it has not been updated in 3 months.

We apologize if this causes any inconvenience. We ask that if you are still encountering this issue, please log a new issue with updated information and we will investigate.
