### ISSUE TITLE
ASP.NET Core 1.1 web application does not start when running with IIS Express in Visual Studio 2017

### ISSUE THREAD

**Issue by series0ne** [aspnet/Home#1982]
I've already raised this issue with [StackOverflow](http://stackoverflow.com/questions/43046220/asp-net-core-1-1-web-application-does-not-start-when-running-with-iis-express-in). This issue may already be addressed elsewhere and apologies if so, but I can't seem to find anything specific, and the suggestions on StackOverflow don't seem to work either:

**Problem**

I've recently installed Visual Studio 2017 Professional and have just created the boilerplate ASP.NET Core Web Application

This is what happens when I hit Run (With IIS Express):

<img src="https://i.stack.imgur.com/UuFOj.png" />

And this is what Visual Studio 2017's Output window says:

> The program '[8260] dotnet.exe' has exited with code -2147450749 (0x80008083).
> The program '[6476] iisexpress.exe' has exited with code 0 (0x0).

Assuming that this is a known issue, are there any steps to fix this, or any available updates to Visual Studio that will fix it?

**Comment by DureSameen** [comment]
I experienced same issue on windows 10, I want to attach IIS Express Trace log files but github does not allow .xml extensions. I have also raised this issue on[ stackoverflow](http://stackoverflow.com/questions/43018425/visual-studio-2017-cannot-launch-iis-express-10-0-on-windows-10-0)  but no response.

**Comment by series0ne** [comment]
@DureSameen does running Visual Studio in admin mode yield any better results?

**Comment by DureSameen** [comment]
no, there is no change in admin mode.

**Comment by series0ne** [comment]
@DureSameen I get the same thing when I run a .NET Core console application.

> The program '[17372] dotnet.exe' has exited with code -2147450749 (0x80008083).

**Comment by series0ne** [comment]
@DureSameen try installing the x86 SDK, see if that helps...

https://www.microsoft.com/net/download/core

**Comment by tmcentee** [comment]
A coworker and myself are seeing the same problem on Win7 and Win10 respectively. 

I don't think the dotnet SDK is at fault here considering launching the project manually with `dotnet run` works just fine. It's only when launching from Visual Studio with IIS Express 10. Also, this problem doesn't occur when running a docker-compose project around the same aspnetcore binary.

I read on a different StackOverflow post that someone had success installing IIS8 to get an ASP.NET Core app running, so I'll be trying that here now.

**Comment by tmcentee** [comment]
I found the issue. 

When running an ASP.NET Core app in VS on IIS Express, you have to configure the web host to use IIS Integrations to handle IIS-specific runtime settings (like capturing IIS exceptions, etc.). 

All I had to do was add the following to the WebHostBuilder in a fresh ASP.NET Core web application and it worked fine. 

![image](https://cloud.githubusercontent.com/assets/17259755/24618150/c6fa6b80-185b-11e7-9fc3-b35e07b55ceb.png)

I'm not sure what effect this could have on other dependent projects (like running in docker) but I'll keep investigating as I go along with a new project we're starting.

**Comment by tmcentee** [comment]
Considering a default dotnetcore project shouldn't have IIS configs in the template, I can see why it was left out. But it would be nice to contact the correct party to make sure something like that is setup when generating a project in VS, since IIS is the default server option in the project currently.

**Comment by Tratcher** [comment]
This won't matter as much after https://github.com/aspnet/Templates/issues/837, we won't need UseIISIntegration in any templates anymore.

Also note that UseIISIntegration is a no-op if you launch your site outside of IIS/Express.

**Comment by DureSameen** [comment]
I found the workaround.

The main issue was My machine already had Visual Studio 2015 Community Edition with updates side by side of Visual Studio 2017.

I removed it and then I tried to remove all individual program beginning with word Core (SDK and run time etc).

Then I remove .NET Core Command-Line Interface (CLI) Tools after that Visual Studio 2017 worked like a charm.

**Comment by wgrs** [comment]
This issue still persists after months of reporting it and has not been fixed.  Yesterday, I downloaded the latest VS2017 15.1 updates and no fixes have been put in place.

**Comment by the-super-coder** [comment]
One of my colleagues is having the same issue. Dot net Run works fine, however we need IIS-Express for debugging. Ironically, only MVC project is having not running but Web Api project runs fine.

He also has VS2015 installed previously, and that needs to be installed as he has to work on a legacy project which was built on VS2015.

Any advice will be appreciated. Thanks.

**Comment by MaximRouiller** [comment]
@series0ne As this bug been resolved for you?

@the-super-coder Have you tried the suggested fix in this page? If it doesn't work, please open a new bug with reproduction step to your problem.

**Comment by the-super-coder** [comment]
My Colleague Umer was having this issue, I suggested the fixes on this issue but that did not work. He needs VS2015 and VS2017 both installed. So he has created a new issue here:
https://github.com/aspnet/Home/issues/2041

**Comment by PeterKottas** [comment]
Hey gents, hope all is well. I was struggling with this as well and it seems like I might have found the solution. What works for me is closing the solution, navigating to where you keep the solution file and deleting .vs folder. Then open again and it works. It's obviously a workaround but at least a quick one. Also it seems it happens when I pull a lot of new projects via git. So that might be causing it somehow. Good luck!

**Comment by the-super-coder** [comment]
Hi @PeterKottas,
Thanks for contributing.

@umerwaheed,
Could you please try if this temporary workaround could get us working?

**Comment by umerwaheed** [comment]
@PeterKottas  @the-super-coder  still not working :(.

**Comment by philblackburn** [comment]
I had this same issue and after digging around for a while I discovered that I had dotnet preview v1.0.0-preview2 installed under Programs Files (x86) and a non-preview version in x64.   I think VS is launching the x86 (preview) version but expecting to see the full version.   To fix this, I did the following.

- from programs and feature uninstall every visible dotnet core.  (note: this did not remove the x86 preview)
- go to https://www.microsoft.com/net/download/core#/sdk and install BOTH x86 and x64 SDK packages
- open command line and from the root directory check run:  dotnet --version   (at the time of writting it was 1.0.4
- fire up .net core project in VS 2017 and run. 

When I did all of the above, I was able to start up the site in IIS Express from VS.

For the record:  you dont need to run VS in administrator mode (unless your targeting full-blown IIS)

**Comment by reminvestor** [comment]
@philblackburn solution worked for me

**Comment by dguisinger** [comment]
So... I had this issue using IIS Express as well, I switched to self-hosting all of my microservices... I have a project with about 10 ASP.NET Core web-api projects.

Unfortunately that didn't fully solve the issue.... Visual Studio now launches a bunch of windows for the Kestrel sessions, but randomly, some don't do anything, they just sit there idle with no text, and the browser windows only open up for the ones actively doing something.  So frustrating when you waste hours a week just trying to get a stable debug session going...I don't know if there is a separate issue reported for that somewhere or if it falls under the same issue.

**Comment by AlphaBlend1975** [comment]
what a problem in my environment
Running Ubuntu 16.04TLS / nginx /.NetCore 2.0 
Error when using systemctl status error and service didnot start 
Working on Widows and IIS Environment

-------------------------------------------------------------------
sudo systemctl status n2nplatform.service
n2nplatform.service - N2NPlatform
   Loaded: loaded (/etc/systemd/system/n2nplatform.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2017-10-18 09:15:36 ICT; 1s ago
  Process: 42579 ExecStart=/usr/bin/dotnet /usr/share/nginx/n2nplatform.com/N2N.dll (code=exited, status=1/FAILURE)
 Main PID: 42579 (code=exited, status=1/FAILURE)

Oct 18 09:15:36 ubuntu16 systemd[1]: n2nplatform.service: Main process exited, code=exited, status=1/FAILURE
Oct 18 09:15:36 ubuntu16 systemd[1]: n2nplatform.service: Unit entered failed state.
Oct 18 09:15:36 ubuntu16 systemd[1]: n2nplatform.service: Failed with result 'exit-code'.

**Comment by wgutierrezr** [comment]
I have the same issue with Core 2 it suddenly stops working. "The site can't be reached" is the only message.

**Comment by BeLumbreras** [comment]
Change the localhost port
Properties of Project --> Web --> URL Project localhost:15115 -->Create virtual directory
SAVE and RUN
Good luck

**Comment by Eilon** [comment]
Closing this because there have been several releases of .NET Core and Visual Studio since this issue was opened, and many bugs have been fixed that might have addressed this. If anyone is still running into this, please log a new issue with details. Thanks!

**Comment by dguisinger** [comment]
FYI This was still happening with Visual Studio 15.7.4 and .NET Core 2.0.3, our team encounters this countless times every day.   We have not yet upgraded to 2.1.x.

**Comment by Eilon** [comment]
To report VS issues, it's best to use the [Report a Problem](https://developercommunity.visualstudio.com/) tool.

If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks. See [here](https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us) for more details.

**Comment by mattiaskjellsson** [comment]
> Hey gents, hope all is well. I was struggling with this as well and it seems like I might have found the solution. What works for me is closing the solution, navigating to where you keep the solution file and deleting .vs folder. Then open again and it works. It's obviously a workaround but at least a quick one. Also it seems it happens when I pull a lot of new projects via git. So that might be causing it somehow. Good luck!

This solved my issue. Thanks a bunch!

**Comment by manpreet11sep** [comment]
Uncheck EnableSSL, shows up the website with broken CSS, atleast something better then nothing. I will go from here.
