### ISSUE TITLE
Flaky test: No_exception_on_diagnostic_event_received_when_null_state

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Home#2844]
I set `No_exception_on_diagnostic_event_received_when_null_state` to ignore for now because it [fails](http://aspnetci/viewLog.html?buildId=398653&tab=buildResultsDiv&buildTypeId=Lite_MvcTest#testNameId-1191126155908700483) sometimes. It should be investigated and re-enabled once fixed.

```
System.Data.SqlClient.SqlException : A connection was successfully established with the server, but then an error occurred during the login process. (provider: Named Pipes Provider, error: 0 - No process is on the other end of the pipe.)
```

**Comment by Eilon** [comment]
@ajcvickers - can you assign someone to take a look at this flaky test?

**Comment by ajcvickers** [comment]
Potentially fixed by: https://github.com/aspnet/Diagnostics/pull/435

**Comment by ryanbrandenburg** [comment]
[Not fixed](http://aspnetci/viewLog.html?buildId=443757&tab=buildResultsDiv&buildTypeId=Lite_EntityFrameworkTest). Future instances of this failure will appear [here](http://aspnetci/httpAuth/app/rest/builds?locator=tag:LoginError,sinceDate:201710010T000000-0001&fields=build(startDate,buildTypeId,status,branchName,webUrl,tags)).
